### ISSUE TITLE
Fallback for browsers that don't support WebAssembly

### ISSUE THREAD

**Issue by christosnc** [NeekSandhu/onigasm#15]
Hello,

Could an ASM fallback be added, just in case, for browsers not supporting WebAssembly?

Then, in the load function there could be a check for WebAssembly support and load appropriately.

*If I'm missing something, please let me know!

Thank you,
- christosnc

**Comment by NeekSandhu** [comment]
Good point! I did consider and even try it a few months back but I gave up for some reason (can't remember what was it).

But as `onigasm` popularity has grown since then, I think it might be worthwhile revisiting that again.

Expect an update on this matter within 2-3 days.

**Comment by NeekSandhu** [comment]
After spending 5 hours on trying to make this work, the verdict is that `WASM` and `ASM` have quite a few technical differences in how they behave, how they are loaded and managed by the emscripten runtime ("glue" code)

Not only this is super hard to do (because Emscripten compiler doesn't provide a clean solution to have a fallback mechanism), but also it not worth the effort.

`onigasm` is used in projects and apps which are used by developers. And developers, for the most part, are using latest and greatest browsers. Moreover, an year from now, most mainstream browsers will have stable support for WebAssembly making this feature not so worthy.

**Comment by NeekSandhu** [comment]
Closing as stale
